### ISSUE TITLE
Not working with current patch?! :(

### ISSUE THREAD

**Issue by teraoo** [Arno736/AGQ#1]

**Comment by Arno736** [comment]
Try with this opcode :
[Opcodes.zip](https://github.com/Arno736/AGQ/files/6071214/Opcodes.zip)

You need to put opcodes file in "\TeraToolbox\data\opcodes\"
Waiting for your return

**Comment by teraoo** [comment]
ok works now  maybe errors in my op codes thanks to you :)
you are super nice
